---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: ansible-automation-platform-operator
spec:
    name: ansible-automation-platform-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    channel: stable-2.3-cluster-scoped
    installPlanApproval: Automatic