app:
  title: Backstage on OpenShift
  baseUrl: https://${bs_app_name}-backstage-backstage.${openshift_ingress_domain}/

organization:
  name: Red Hat

backend:
  baseUrl: https://${bs_app_name}-backstage-backstage.${openshift_ingress_domain}/
  database:
    client: pg
    connection:
      # config options: https://node-postgres.com/apis/client
      host: ${bs_app_name}-backstage-pgcluster-rw
      port: 5432
      user: ${username}
      password: ${password}
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # https://node-postgres.com/features/ssl
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      ssl:
        ca: # if you have a CA file and want to verify it you can uncomment this section
          $file: /var/run/secrets/backstage-pgcluster-ca
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/tutorials/backend-to-backend-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  listen:
    port: 7007
  #   # Uncomment the following host directive to bind to specific interfaces
  #   # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  cache:
    store: memory
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      ## if using a PAT
      # token: ${GITHUB_TOKEN}
      ## if using GitHub apps
      apps:
        - $include: github-app-credentials.yaml

github-org-provider:
  id: production
  orgUrl: https://github.com/joshgav-org

proxy:
  '/quay/api':
    target: https://quay.io/
    headers:
      X-Requested-With: 'XMLHttpRequest'
      # Uncomment the following line to access a private Quay Repository using a token
      # Authorization: 'Bearer <YOUR TOKEN>'
    changeOrigin: true
    secure: true
  '/argocd/api':
    target: https://openshift-gitops-server-openshift-gitops.${openshift_ingress_domain}/api/v1
    changeOrigin: true
    secure: true
    pathRewrite:
      '^/api/proxy/argocd/api': '/'
    headers:
      # inject token as env var from secret
      Authorization: 'Bearer ${ARGOCD_AUTH_TOKEN}'

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers: {}

scaffolder: {}

catalog:
  ## examples
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    # example files must be copied into the container
    # TODO: enable Helm chart to transit files as config maps
    # See # https://backstage.io/docs/features/software-catalog/software-catalog-overview#adding-components-to-the-catalog
    # for more details on how to get entities into the catalog.
    - type: file
      target: examples/entities.yaml
    - type: file
      target: examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: examples/org.yaml
      rules:
        - allow: [User, Group]
    - type: url
      target: https://github.com/joshgav/devenv/blob/main/apps/apiserver/catalog-info.yaml
    # Janus (Red Hat) templates
    - type: url
      target: https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml
    # example public data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - url: https://kubernetes.default.svc/
          name: local
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          authProvider: serviceAccount
          # don't specify this attribute to force lookup in pod in cluster
          # serviceAccountToken: ''
          dashboardUrl: https://console-openshift-console.${openshift_ingress_domain}/
          dashboardApp: openshift
          skipTLSVerify: false
          skipMetricsLookup: false

ocm:
  hub:
    name: local
    url: https://kubernetes.default.svc/
